### ISSUE TITLE
Table 'routes' not populated

### ISSUE THREAD

**Issue by joubu** [pders01/koha-plugin-command-palette#1]
commit c8c1522c77f removed the Routes->extract call and the table is never populated. Hence `routes?path=a` always returns 404.

**Comment by pders01** [comment]
Ah, I must have deleted that by mistake. On the other hand I think I'll move the population into the install hook for now. Then I will also delete the index table as the Trie DS acts as the new 'index'.

**Comment by pders01** [comment]
Should work now.
