### ISSUE TITLE
Ctrl+Shift+P shortcut is not ideal

### ISSUE THREAD

**Issue by joubu** [pders01/koha-plugin-command-palette#2]
It opens a new private window in Firefox.

**Comment by pders01** [comment]
Yeah, you're right. Didn't run into this issue on mac but the rest of the world will. Maybe ctrl + j is a better choice.

**Comment by pders01** [comment]
I've changed the shortcut to Ctrl|Cmd + / for now. Shouldn't conflict w/ anything but we still have the modifier guard.
